version: '3.8'
services:
  rp-next:
    build:
      context: ./rp-next
      dockerfile: Dockerfile
    volumes:
      - ./rp-next:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  rp-python:
    build:
      context: ./rp-python
      dockerfile: Dockerfile
    volumes:
      - ./rp-python/src:/app/src
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  rp-go:
    build:
      context: ./rp-go
      dockerfile: Dockerfile
    volumes:
      - ./rp-go/:/app
    ports:
      - "8000:8080"

  rp-nest:
    build:
      context: ./rp-nest
      dockerfile: Dockerfile
    volumes:
      - ./rp-nest:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
        interval: 1s
        retries: 10
        test: ["CMD", "pg_isready", "-U", "postgres"]
    ports: 
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
